# Generated by Django 4.2.1 on 2023-07-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterField(
            model_name='provider',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Coffee house')], default=1, verbose_name='kind'),
        ),
    ]
