# Generated by Django 4.2.1 on 2023-08-29 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0002_alter_client_city_alter_client_owner_and_more'),
        ('biz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(verbose_name='total price')),
                ('takeaway_order', models.BooleanField(default=False)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Sent'), (2, 'Complete'), (3, 'No show')], default=1, verbose_name='status')),
                ('order_datatime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='order datatime')),
                ('owner', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Product')),
                ('price', models.FloatField()),
                ('description', models.CharField(blank=True, default='', max_length=1024, verbose_name='Description')),
                ('gluten', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AddField(
            model_name='provider',
            name='description',
            field=models.CharField(blank=True, max_length=2048, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='provider',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=512, verbose_name='facebook link'),
        ),
        migrations.AddField(
            model_name='provider',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=512, verbose_name='instagram link'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Coffee house')], default=1, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biz.product')),
            ],
            options={
                'verbose_name': 'Cake',
                'verbose_name_plural': 'Cakes',
            },
            bases=('biz.product',),
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biz.product')),
            ],
            options={
                'verbose_name': 'Coffee',
                'verbose_name_plural': 'Coffees',
            },
            bases=('biz.product',),
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biz.product')),
            ],
            options={
                'verbose_name': 'Snack',
                'verbose_name_plural': 'Snacks',
            },
            bases=('biz.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='biz.provider', verbose_name='owner'),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_amount', models.IntegerField()),
                ('name', models.CharField(default='Table', max_length=256, verbose_name='Table')),
                ('availability', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='biz.provider', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_change', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Sent'), (2, 'Complete'), (3, 'No show')], null=True, verbose_name='status')),
                ('order_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='biz.order')),
            ],
            options={
                'verbose_name': 'Order history',
                'verbose_name_plural': 'Orders history',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='biz.provider'),
        ),
        migrations.AddField(
            model_name='order',
            name='spot',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='biz.place', verbose_name='spot'),
        ),
        migrations.CreateModel(
            name='OpenDayProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=True)),
                ('monday_from', models.TimeField(blank=True, default=None, null=True)),
                ('monday_to', models.TimeField(blank=True, default=None, null=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('tuesday_from', models.TimeField(blank=True, default=None, null=True)),
                ('tuesday_to', models.TimeField(blank=True, default=None, null=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('wednesday_from', models.TimeField(blank=True, default=None, null=True)),
                ('wednesday_to', models.TimeField(blank=True, default=None, null=True)),
                ('thursday', models.BooleanField(default=True)),
                ('thursday_from', models.TimeField(blank=True, default=None, null=True)),
                ('thursday_to', models.TimeField(blank=True, default=None, null=True)),
                ('friday', models.BooleanField(default=True)),
                ('friday_from', models.TimeField(blank=True, default=None, null=True)),
                ('friday_to', models.TimeField(blank=True, default=None, null=True)),
                ('saturday', models.BooleanField(default=True)),
                ('saturday_from', models.TimeField(blank=True, default=None, null=True)),
                ('saturday_to', models.TimeField(blank=True, default=None, null=True)),
                ('sunday', models.BooleanField(default=True)),
                ('sunday_from', models.TimeField(blank=True, default=None, null=True)),
                ('sunday_to', models.TimeField(blank=True, default=None, null=True)),
                ('owner', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='biz.provider')),
            ],
            options={
                'verbose_name': 'Opening day',
                'verbose_name_plural': 'Opening days',
            },
        ),
        migrations.CreateModel(
            name='OrderSnacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='biz.order')),
                ('snacks', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='biz.snacks')),
            ],
            options={
                'verbose_name': 'Snack order',
                'verbose_name_plural': 'Snacks order',
            },
        ),
        migrations.CreateModel(
            name='OrderCoffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='biz.order', verbose_name='order')),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biz.coffee')),
            ],
            options={
                'verbose_name': 'Coffee order',
                'verbose_name_plural': 'Coffees order',
            },
        ),
        migrations.CreateModel(
            name='OrderCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='biz.order')),
                ('cake', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='biz.cake')),
            ],
            options={
                'verbose_name': 'Cake order',
                'verbose_name_plural': 'Cakes order',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cakes',
            field=models.ManyToManyField(through='biz.OrderCake', to='biz.cake', verbose_name='cakes'),
        ),
        migrations.AddField(
            model_name='order',
            name='coffees',
            field=models.ManyToManyField(through='biz.OrderCoffee', to='biz.coffee', verbose_name='coffees'),
        ),
        migrations.AddField(
            model_name='order',
            name='snacks',
            field=models.ManyToManyField(through='biz.OrderSnacks', to='biz.snacks', verbose_name='snacks'),
        ),
    ]
