# Generated by Django 4.1.4 on 2023-07-20 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0002_alter_provider_options_alter_provider_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDayProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=True)),
                ('monday_from', models.TimeField(default=None)),
                ('monday_to', models.TimeField(default=None)),
                ('tuesday', models.BooleanField(default=True)),
                ('tuesday_from', models.TimeField(default=None)),
                ('tuesday_to', models.TimeField(default=None)),
                ('wednesday', models.BooleanField(default=True)),
                ('wednesday_from', models.TimeField(default=None)),
                ('wednesday_to', models.TimeField(default=None)),
                ('thursday', models.BooleanField(default=True)),
                ('thursday_from', models.TimeField(default=None)),
                ('thursday_to', models.TimeField(default=None)),
                ('friday', models.BooleanField(default=True)),
                ('friday_from', models.TimeField(default=None)),
                ('friday_to', models.TimeField(default=None)),
                ('saturday', models.BooleanField(default=True)),
                ('saturday_from', models.TimeField(default=None)),
                ('saturday_to', models.TimeField(default=None)),
                ('sunday', models.BooleanField(default=True)),
                ('sunday_from', models.TimeField(default=None)),
                ('sunday_to', models.TimeField(default=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biz.provider')),
            ],
        ),
    ]
