# Generated by Django 4.2.1 on 2023-08-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0002_order_product_alter_provider_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opendayprovider',
            options={'verbose_name': 'Opening day', 'verbose_name_plural': 'Opening days'},
        ),
    ]
