# Generated by Django 4.2.1 on 2023-07-21 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0003_opendayprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Coffee')),
                ('price', models.FloatField()),
                ('description', models.CharField(default='', max_length=1024, verbose_name='Description')),
                ('gluten', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biz.product')),
            ],
            options={
                'verbose_name': 'Coffee',
                'verbose_name_plural': 'Coffees',
            },
            bases=('biz.product',),
        ),
    ]
