# Generated by Django 4.2.1 on 2023-07-21 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biz', '0004_product_coffee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biz.product')),
            ],
            options={
                'verbose_name': 'Cake',
                'verbose_name_plural': 'Cakes',
            },
            bases=('biz.product',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(verbose_name='total price')),
                ('takeaway_order', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Sent'), (2, 'Complete'), (3, 'No show')], null=True, verbose_name='status')),
                ('order_datatime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='order datatime')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_amount', models.IntegerField()),
                ('name', models.CharField(default='Table', max_length=256, verbose_name='Table')),
                ('availability', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biz.product')),
            ],
            options={
                'verbose_name': 'Snack',
                'verbose_name_plural': 'Snacks',
            },
            bases=('biz.product',),
        ),
        migrations.CreateModel(
            name='OrderSnacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biz.order')),
                ('snacks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biz.snacks')),
            ],
            options={
                'verbose_name': 'Snack order',
                'verbose_name_plural': 'Snacks order',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_change', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Sent'), (2, 'Complete'), (3, 'No show')], null=True, verbose_name='status')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biz.order')),
            ],
            options={
                'verbose_name': 'Order history',
                'verbose_name_plural': 'Orders history',
            },
        ),
        migrations.CreateModel(
            name='OrderCoffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biz.coffee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biz.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Coffee order',
                'verbose_name_plural': 'Coffees order',
            },
        ),
        migrations.CreateModel(
            name='OrderCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biz.cake')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biz.order')),
            ],
            options={
                'verbose_name': 'Cake order',
                'verbose_name_plural': 'Cakes order',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cakes',
            field=models.ManyToManyField(through='biz.OrderCake', to='biz.cake', verbose_name='cakes'),
        ),
        migrations.AddField(
            model_name='order',
            name='coffees',
            field=models.ManyToManyField(through='biz.OrderCoffee', to='biz.coffee', verbose_name='coffees'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
        migrations.AddField(
            model_name='order',
            name='snacks',
            field=models.ManyToManyField(through='biz.OrderSnacks', to='biz.snacks', verbose_name='snacks'),
        ),
        migrations.AddField(
            model_name='order',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biz.place', verbose_name='spot'),
        ),
    ]
