# Generated by Django 4.2.1 on 2023-07-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0005_cake_order_place_snacks_ordersnacks_orderhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biz.provider', verbose_name='owner'),
            preserve_default=False,
        ),
    ]
