# Generated by Django 4.2.1 on 2023-07-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0006_product_active_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='description',
            field=models.CharField(default='', max_length=2048, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='provider',
            name='facebook_link',
            field=models.CharField(default='', max_length=512, verbose_name='facebook link'),
        ),
        migrations.AddField(
            model_name='provider',
            name='instagram_link',
            field=models.CharField(default='', max_length=512, verbose_name='instagram link'),
        ),
    ]
