# Generated by Django 4.1.4 on 2023-07-13 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Kawa')),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Kawa',
                'verbose_name_plural': 'Kawy',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Ciastko')),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Ciasto',
                'verbose_name_plural': 'Ciasta',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_amount', models.IntegerField()),
                ('name', models.CharField(default='Stolik', max_length=256, verbose_name='Stolik')),
            ],
            options={
                'verbose_name': 'Stolik',
                'verbose_name_plural': 'Stoliki',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1024, unique=True, verbose_name=uuid.UUID('48d197bc-0942-4e0d-b400-8e1db4855281'))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(verbose_name='total price')),
                ('coffee_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coffee', verbose_name='cafe order')),
                ('cake_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cake', verbose_name='cake order')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.place', verbose_name='spot')),
            ],
            options={
                'verbose_name': 'Zamówienie',
                'verbose_name_plural': 'Zamówienia',
            },
        ),
    ]
