# Generated by Django 4.2.1 on 2023-08-29 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cake_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coffee_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='spot',
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name': 'User token', 'verbose_name_plural': 'Users token'},
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('bdd0e8fa-248c-44df-a62c-1158c6df8bcd'), max_length=1024, unique=True),
        ),
        migrations.DeleteModel(
            name='Cake',
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
