# Generated by Django 4.2.1 on 2023-09-12 06:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_order_cake_order_remove_order_coffee_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('ad443bf7-4773-42d5-8f7b-36e36cca4828'), max_length=1024, unique=True),
        ),
    ]
