# Generated by Django 4.1.4 on 2023-07-14 19:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('core', '0002_alter_usertoken_options_alter_usertoken_token_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('06092ab3-0e3f-4431-9e24-9fb026d3d121'), max_length=1024, unique=True),
        ),
    ]
