# Generated by Django 4.1.4 on 2023-07-15 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_usertoken_owner_alter_usertoken_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Przekąski')),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Przekąska',
                'verbose_name_plural': 'Przekąski',
            },
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name': 'Token użytkownika', 'verbose_name_plural': 'Tokeny użytkowników'},
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='użytkownik', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('bcbfcd27-15d8-4d27-a958-bfd4f6fb9a63'), max_length=1024, unique=True),
        ),
    ]
