# Generated by Django 4.1.4 on 2023-07-15 09:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_snacks_alter_usertoken_options_alter_usertoken_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coffee_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cake_order',
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('3583d110-a168-4ac2-b975-87b76aaa0b0b'), max_length=1024, unique=True),
        ),
        migrations.CreateModel(
            name='OrderSnacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('snacks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.snacks')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCoffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coffee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cake')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cakes',
            field=models.ManyToManyField(through='core.OrderCake', to='core.cake', verbose_name='cakes'),
        ),
        migrations.AddField(
            model_name='order',
            name='coffees',
            field=models.ManyToManyField(through='core.OrderCoffee', to='core.coffee', verbose_name='coffees'),
        ),
        migrations.AddField(
            model_name='order',
            name='snacks',
            field=models.ManyToManyField(through='core.OrderSnacks', to='core.snacks', verbose_name='snacks'),
        ),
    ]
