# Generated by Django 4.1.4 on 2023-07-16 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usertoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coffee',
            name='gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snacks',
            name='gluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('90ef2ce0-7309-4be6-ad74-712b61357175'), max_length=1024, unique=True),
        ),
    ]
