# Generated by Django 4.2.1 on 2023-07-19 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cake_gluten_coffee_gluten_snacks_gluten_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Wysłane'), (2, 'Przyjęte'), (3, 'Realizacja'), (4, 'Zakończone')], null=True, verbose_name='player_position'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('ea05a714-7cdc-4317-b32a-de62e44687d8'), max_length=1024, unique=True),
        ),
    ]
