# Generated by Django 4.2.1 on 2023-07-19 07:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_status_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Wysłane'), (2, 'Przyjęte'), (3, 'Realizacja'), (4, 'Zakończone')], null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('053780df-2ccd-47c3-b6a3-c4ede3c2a068'), max_length=1024, unique=True),
        ),
    ]
