# Generated by Django 4.2.1 on 2023-07-19 07:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_order_status_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('45108975-98b2-49d7-941b-524f718797da'), max_length=1024, unique=True),
        ),
    ]
