# Generated by Django 4.2.1 on 2023-07-19 07:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('6cde900e-db32-4957-9a35-bf03dd5511bf'), max_length=1024, unique=True),
        ),
    ]
