# Generated by Django 4.2.1 on 2023-07-19 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('6564a152-a1da-4bdb-978b-4ed817218b59'), max_length=1024, unique=True),
        ),
    ]
