# Generated by Django 4.2.1 on 2023-07-19 08:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('2a81af1c-96dd-44f7-ab1b-e663d15922cb'), max_length=1024, unique=True),
        ),
    ]
