# Generated by Django 4.2.1 on 2023-07-19 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name': 'Cake', 'verbose_name_plural': 'Cakes'},
        ),
        migrations.AlterModelOptions(
            name='coffee',
            options={'verbose_name': 'Coffee', 'verbose_name_plural': 'Coffees'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='ordercake',
            options={'verbose_name': 'Cake order', 'verbose_name_plural': 'Cakes order'},
        ),
        migrations.AlterModelOptions(
            name='ordercoffee',
            options={'verbose_name': 'Coffee order', 'verbose_name_plural': 'Coffees order'},
        ),
        migrations.AlterModelOptions(
            name='ordersnacks',
            options={'verbose_name': 'Snack order', 'verbose_name_plural': 'Snacks order'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.AlterModelOptions(
            name='snacks',
            options={'verbose_name': 'Snack', 'verbose_name_plural': 'Snacks'},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name': 'User token', 'verbose_name_plural': 'Users token'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_datatime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='order datatime'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sent'), (2, 'Accepted'), (3, 'Processing'), (4, 'Complete')], null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(default='Table', max_length=256, verbose_name='Table'),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Snacks'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('120cca77-9293-4adc-8521-bf1a2639a26b'), max_length=1024, unique=True),
        ),
    ]
