# Generated by Django 4.2.1 on 2023-07-19 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_cake_options_alter_coffee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('84a67d26-39e6-4a26-99e7-7215e1b0d22e'), max_length=1024, unique=True),
        ),
    ]
