# Generated by Django 4.2.1 on 2023-07-20 07:09

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_order_status_alter_usertoken_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name': 'Order history', 'verbose_name_plural': 'Orders history'},
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sent'), (2, 'Complete'), (3, 'No show')], null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('fa5a10bd-9248-4243-af5c-980197bfe201'), max_length=1024, unique=True),
        ),
    ]
