# Generated by Django 4.2.1 on 2023-07-20 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_orderhistory_options_orderhistory_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sent'), (2, 'Complete'), (3, 'No show')], null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('76878077-0420-4a8b-a71f-f0af66e33c65'), max_length=1024, unique=True),
        ),
    ]
