# Generated by Django 4.2.1 on 2023-07-20 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_orderhistory_status_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('49f3edd5-15c8-403e-9a1f-0a3d8bff6f7c'), max_length=1024, unique=True),
        ),
    ]
