# Generated by Django 4.2.1 on 2023-07-20 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('f103d69e-2e12-4e5f-8cbd-78226f0858be'), max_length=1024, unique=True),
        ),
    ]
