# Generated by Django 4.2.1 on 2023-07-20 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('01eec8e4-4522-4f05-b77c-079bfffdc366'), max_length=1024, unique=True),
        ),
    ]
