# Generated by Django 4.2.1 on 2023-07-20 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('8d496239-be0b-47d6-a7ce-69f9dcab8093'), max_length=1024, unique=True),
        ),
    ]
