# Generated by Django 4.2.1 on 2023-07-20 10:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('0242ca92-3093-4c2f-af6b-63c6e06b06f0'), max_length=1024, unique=True),
        ),
    ]
