# Generated by Django 4.2.1 on 2023-07-20 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('e50c3f81-2266-4f39-aa1c-c2feea960b22'), max_length=1024, unique=True),
        ),
    ]
