# Generated by Django 4.1.4 on 2023-07-20 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('ab09899d-0804-486a-89b4-438183c4cf99'), max_length=1024, unique=True),
        ),
    ]
