# Generated by Django 4.2.1 on 2023-07-21 08:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercoffee',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('0dd5784e-7520-4a2d-92c6-88fc12ce036e'), max_length=1024, unique=True),
        ),
    ]
