# Generated by Django 4.2.1 on 2023-07-21 08:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_ordercoffee_order_alter_usertoken_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cakes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coffees',
        ),
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='order',
            name='snacks',
        ),
        migrations.RemoveField(
            model_name='order',
            name='spot',
        ),
        migrations.RemoveField(
            model_name='ordercake',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='ordercake',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordercoffee',
            name='coffee',
        ),
        migrations.RemoveField(
            model_name='ordercoffee',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='ordersnacks',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordersnacks',
            name='snacks',
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('8a047878-ab82-42e8-ad36-60ceb6512bb5'), max_length=1024, unique=True),
        ),
        migrations.DeleteModel(
            name='Cake',
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderCake',
        ),
        migrations.DeleteModel(
            name='OrderCoffee',
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
        migrations.DeleteModel(
            name='OrderSnacks',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Snacks',
        ),
    ]
