# Generated by Django 4.2.1 on 2023-07-21 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_order_cakes_remove_order_coffees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('aa3b4dd3-ab1f-4745-a2f0-a550fbb2c632'), max_length=1024, unique=True),
        ),
    ]
