# Generated by Django 4.2.1 on 2023-07-21 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('61b7f08b-4e1c-4b84-b213-0c5894e8bd03'), max_length=1024, unique=True),
        ),
    ]
