# Generated by Django 4.2.1 on 2023-07-21 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('cc9d55c1-5955-4a60-94f8-c52416a3d52d'), max_length=1024, unique=True),
        ),
    ]
