# Generated by Django 4.2.1 on 2023-07-27 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('81eb6620-2b7c-4c89-a737-19d26f42d894'), max_length=1024, unique=True),
        ),
    ]
