# Generated by Django 4.2.1 on 2023-07-27 06:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('17b02a48-e4f6-4dac-80be-5bab5e472a3c'), max_length=1024, unique=True),
        ),
    ]
