# Generated by Django 4.2.1 on 2023-07-27 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('4b718a2a-f0ae-459f-8c7c-b2ef27ec968a'), max_length=1024, unique=True),
        ),
    ]
