# Generated by Django 4.2.1 on 2023-07-27 07:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('b80d6b86-2491-4cfb-a776-4954810c1885'), max_length=1024, unique=True),
        ),
    ]
