# Generated by Django 4.2.1 on 2023-07-27 07:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('154a0041-aa0d-4f93-a62c-ff335a776ec1'), max_length=1024, unique=True),
        ),
    ]
