# Generated by Django 4.2.1 on 2023-07-27 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('a9bb02b7-c01a-47f3-b690-d2c32fa09878'), max_length=1024, unique=True),
        ),
    ]
