# Generated by Django 4.2.1 on 2023-07-27 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('ce30edf3-92be-4bc5-ae14-b755d2460ca5'), max_length=1024, unique=True),
        ),
    ]
