# Generated by Django 4.2.1 on 2023-07-27 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('e10319bd-c100-42ca-863d-7fe043a21ab6'), max_length=1024, unique=True),
        ),
    ]
