# Generated by Django 4.2.1 on 2023-07-27 07:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('0dee2f4f-59a3-4f2a-a015-fc4f0b8b1b4c'), max_length=1024, unique=True),
        ),
    ]
