# Generated by Django 4.2.1 on 2023-07-27 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('9b3125a1-36e6-4b18-8ff8-86dba4d4ada7'), max_length=1024, unique=True),
        ),
    ]
