# Generated by Django 4.2.1 on 2023-08-25 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('f611edc6-f381-45aa-b0e4-275f2d41b4f6'), max_length=1024, unique=True),
        ),
    ]
