# Generated by Django 4.2.1 on 2023-08-25 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('e4350fe0-041e-4cd6-b4ed-77f17e07b04a'), max_length=1024, unique=True),
        ),
    ]
