# Generated by Django 4.2.1 on 2023-08-26 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('08010f79-29ba-4ed2-af9b-1ac89a636429'), max_length=1024, unique=True),
        ),
    ]
