# Generated by Django 4.2.1 on 2023-08-26 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('d8b8a501-369a-42bd-b8a1-a78889eaa12d'), max_length=1024, unique=True),
        ),
    ]
