# Generated by Django 4.2.1 on 2023-08-26 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('7f61540e-d978-4590-9e88-d0870428c2d7'), max_length=1024, unique=True),
        ),
    ]
