# Generated by Django 4.2.1 on 2023-08-26 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('e7365703-4e8c-4fe2-8b99-2d38abedc295'), max_length=1024, unique=True),
        ),
    ]
