# Generated by Django 4.2.1 on 2023-08-26 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(default=uuid.UUID('1a4a62f3-15ef-4555-874f-3718489801fa'), max_length=1024, unique=True),
        ),
    ]
